# Generated by Django 5.0.5 on 2025-05-17 17:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ppt', 'pptx'])], verbose_name='Файл')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentauthor', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Начальная презентация',
                'verbose_name_plural': 'Начальные презентации',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='MainDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='maindocuments', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ppt', 'pptx'])], verbose_name='Сформированный файл')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата формирования')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainauthor', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сформированная презентация',
                'verbose_name_plural': 'Сформированные презентации',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='SampleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sampledocuments', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ppt', 'pptx'])], verbose_name='Титульные слайды')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampleauthor', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Титульный шаблон презентации',
                'verbose_name_plural': 'Титульные шаблоны презентации',
                'ordering': ['-pk'],
            },
        ),
    ]
